name: 'GH Release Manager'
description: 'Automatically update version file based on GitHub release tag'
inputs:
  lang:
    description: 'Language of the project (e.g., rust, js, etc.)'
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/chrisllontop/gh-release-manager:v1'
  env:
    INPUT_LANG: ${{ inputs.lang }}
