[package]
name = "gh_release_manager"
version = "1.0.3"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.116"
toml = "0.8.12"
regex = "1.10.4"
thiserror = "1.0"
anyhow = "1.0"

[dependencies.serde_derive]
version = "1.0"
